version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5002"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/chatapp
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules


volumes:
  mongodb_data:
